"""_build_wordbank.py — 一次性生成 data/wordbank/{primary,middle,high}.json
覆盖 K-12 课标全量近似 5100 词；合并现有 200 词手写例句。

DSL 规则:
  - 每行 "word|meaning|pos" 或 "word|meaning"（pos 默认 n）或 "word|meaning|pos|diff"
  - "=== topic ===" 切换主题
  - "// xxx" 是注释
"""
import json
import re
from pathlib import Path

OUT = Path("data/wordbank")
OUT.mkdir(parents=True, exist_ok=True)

# ─────────────────────────  小学 600+ 词  ─────────────────────────
PRIMARY = """\
=== basic ===
hi|嗨|int
oh|哦|int
ok|好的|adv
sure|当然|adv
fine|好的|adj
well|好的|adv
today|今天|n
tonight|今晚|n
here|这里|adv
there|那里|adv
this|这个|pron
that|那个|pron
these|这些|pron
those|那些|pron
who|谁|pron
what|什么|pron
where|哪里|adv
when|何时|adv
why|为什么|adv
how|怎么|adv
again|再次|adv
also|也|adv
very|非常|adv
much|许多|adj
more|更多|adv
all|全部|adj
some|一些|adj
any|任何|adj
every|每个|adj
never|从不|adv
always|总是|adv
sometimes|有时|adv
often|经常|adv
nice|好的|adj
kind|友善的|adj
smart|聪明的|adj
busy|忙的|adj
free|空闲的|adj
easy|容易的|adj
hard|困难的|adj
quick|快的|adj
slow|慢的|adj
late|迟的|adj
early|早的|adj
soon|很快|adv
now|现在|adv
then|然后|adv
just|只是|adv
still|仍然|adv
yet|还|adv
miss|想念|v
try|尝试|v
can|能|v
may|可以|v
will|将|v
must|必须|v
should|应该|v
old|老的|adj
young|年轻的|adj
new|新的|adj
good|好的|adj
bad|坏的|adj
right|对的|adj
wrong|错的|adj
true|真的|adj
ready|准备好|adj
tired|累的|adj
sick|生病的|adj
hungry|饿的|adj
thirsty|渴的|adj
strong|强壮的|adj
weak|虚弱的|adj
both|两者都|pron
each|每个|pron
many|许多|adj
few|很少|adj
=== school ===
bag|书包|n
schoolbag|书包|n
notebook|笔记本|n
paper|纸|n
ink|墨水|n
glue|胶水|n
scissors|剪刀|n
marker|马克笔|n
chalk|粉笔|n
board|黑板|n
math|数学|n
English|英语|n
Chinese|语文|n
science|科学|n
art|美术|n
music|音乐|n
PE|体育|n
chair|椅子|n
desk|课桌|n
exam|考试|n
test|测试|n
quiz|小测|n
grade|年级|n
study|学习|v
learn|学习|v
teach|教|v
class|班级|n
hall|大厅|n
gym|体育馆|n
playground|操场|n
lab|实验室|n
period|课时|n
break|休息|n
holiday|假日|n
vacation|假期|n
uniform|校服|n
dictionary|字典|n
textbook|课本|n
story|故事|n
poem|诗|n
essay|作文|n
notes|笔记|n
page|页|n
line|行|n
word|单词|n
letter|字母|n
sentence|句子|n
question|问题|n
answer|答案|n
homework|家庭作业|n
review|复习|v
memorize|记住|v
spell|拼写|v
translate|翻译|v
correct|正确的|adj
mark|分数|n
plus|加|prep
minus|减|prep
times|乘|prep
divide|除|v
add|加|v
sum|总数|n
read|读|v
listen|听|v
draw|画|v
sing|唱|v
dance|跳舞|v
write|写|v
speak|说|v
report|报告|n
paint|绘画|v
sport|运动|n
team|团队|n
meeting|会议|n
plan|计划|n
=== nature ===
lion|狮子|n
tiger|老虎|n
bear|熊|n
wolf|狼|n
fox|狐狸|n
rabbit|兔子|n
mouse|老鼠|n
horse|马|n
cow|牛|n
pig|猪|n
sheep|羊|n
goat|山羊|n
duck|鸭|n
chicken|鸡|n
hen|母鸡|n
fish|鱼|n
frog|青蛙|n
snake|蛇|n
bee|蜜蜂|n
ant|蚂蚁|n
fly|苍蝇|n
spider|蜘蛛|n
panda|熊猫|n
monkey|猴子|n
deer|鹿|n
dolphin|海豚|n
whale|鲸鱼|n
shark|鲨鱼|n
eagle|鹰|n
owl|猫头鹰|n
parrot|鹦鹉|n
peacock|孔雀|n
goose|鹅|n
swan|天鹅|n
crow|乌鸦|n
sparrow|麻雀|n
pigeon|鸽子|n
swallow|燕子|n
leaf|叶子|n
branch|树枝|n
root|根|n
seed|种子|n
fruit|水果|n
grass|草|n
bush|灌木|n
forest|森林|n
jungle|丛林|n
desert|沙漠|n
ocean|海洋|n
sea|海|n
lake|湖|n
pond|池塘|n
beach|海滩|n
island|岛|n
hill|小山|n
valley|山谷|n
hot|热的|adj
cold|冷的|adj
warm|暖和的|adj
cool|凉爽的|adj
sunny|晴朗的|adj
cloudy|多云的|adj
rainy|多雨的|adj
snowy|多雪的|adj
windy|有风的|adj
foggy|有雾的|adj
stormy|暴风的|adj
ice|冰|n
fire|火|n
wind|风|n
cloud|云|n
star|星星|n
sky|天空|n
ground|地面|n
land|土地|n
field|田野|n
=== food ===
pizza|披萨|n
hamburger|汉堡|n
hotdog|热狗|n
cheese|奶酪|n
butter|黄油|n
jam|果酱|n
honey|蜂蜜|n
sugar|糖|n
salt|盐|n
pepper|胡椒|n
sauce|酱汁|n
soup|汤|n
salad|沙拉|n
pasta|意大利面|n
dumpling|饺子|n
porridge|粥|n
cake|蛋糕|n
cookie|曲奇|n
biscuit|饼干|n
pie|派|n
candy|糖果|n
chocolate|巧克力|n
icecream|冰淇淋|n
popcorn|爆米花|n
donut|甜甜圈|n
cupcake|纸杯蛋糕|n
fruit|水果|n
grape|葡萄|n
strawberry|草莓|n
watermelon|西瓜|n
peach|桃|n
pear|梨|n
plum|李子|n
mango|芒果|n
pineapple|菠萝|n
kiwi|猕猴桃|n
cherry|樱桃|n
lemon|柠檬|n
coconut|椰子|n
tomato|番茄|n
potato|土豆|n
carrot|胡萝卜|n
onion|洋葱|n
garlic|大蒜|n
cucumber|黄瓜|n
lettuce|生菜|n
cabbage|卷心菜|n
mushroom|蘑菇|n
pumpkin|南瓜|n
corn|玉米|n
bean|豆|n
beef|牛肉|n
pork|猪肉|n
shrimp|虾|n
crab|螃蟹|n
fork|叉子|n
spoon|勺子|n
knife|刀|n
chopstick|筷子|n
plate|盘子|n
bowl|碗|n
cup|杯子|n
glass|玻璃杯|n
mug|马克杯|n
bottle|瓶子|n
kettle|水壶|n
pan|平底锅|n
pot|锅|n
oven|烤箱|n
fridge|冰箱|n
sweet|甜的|adj
salty|咸的|adj
sour|酸的|adj
bitter|苦的|adj
spicy|辣的|adj
fresh|新鲜的|adj
=== family ===
parents|父母|n
son|儿子|n
daughter|女儿|n
baby|婴儿|n
child|孩子|n
kid|小孩|n
twin|双胞胎|n
husband|丈夫|n
wife|妻子|n
family|家|n
granddad|爷爷|n
grandpa|爷爷|n
grandma|奶奶|n
granny|奶奶|n
nephew|侄子|n
niece|侄女|n
neighbor|邻居|n
person|人|n
people|人们|n
man|男人|n
woman|女人|n
doctor|医生|n
nurse|护士|n
farmer|农民|n
worker|工人|n
driver|司机|n
cook|厨师|n
waiter|服务员|n
soldier|士兵|n
police|警察|n
postman|邮递员|n
dentist|牙医|n
painter|画家|n
singer|歌手|n
dancer|舞者|n
actor|演员|n
writer|作家|n
reader|读者|n
player|选手|n
helper|帮手|n
partner|伙伴|n
mate|伙伴|n
buddy|兄弟|n
schoolmate|同校同学|n
teammate|队友|n
hero|英雄|n
lady|女士|n
mister|先生|n
gentleman|绅士|n
king|国王|n
queen|王后|n
prince|王子|n
princess|公主|n
captain|队长|n
judge|法官|n
lawyer|律师|n
scientist|科学家|n
engineer|工程师|n
manager|经理|n
boss|老板|n
employee|员工|n
customer|顾客|n
guest|客人|n
visitor|访客|n
stranger|陌生人|n
foreigner|外国人|n
citizen|公民|n
boyfriend|男朋友|n
girlfriend|女朋友|n
roommate|室友|n
=== numtime ===
four|四|num
five|五|num
six|六|num
seven|七|num
eight|八|num
nine|九|num
eleven|十一|num
thirteen|十三|num
fourteen|十四|num
fifteen|十五|num
sixteen|十六|num
seventeen|十七|num
eighteen|十八|num
nineteen|十九|num
thirty|三十|num
forty|四十|num
fifty|五十|num
sixty|六十|num
seventy|七十|num
eighty|八十|num
ninety|九十|num
thousand|千|num
million|百万|num
first|第一|num
second|第二|num
third|第三|num
fourth|第四|num
fifth|第五|num
half|一半|n
quarter|四分之一|n
hour|小时|n
minute|分钟|n
yesterday|昨天|n
midnight|午夜|n
noon|中午|n
night|夜晚|n
dawn|黎明|n
sunrise|日出|n
sunset|日落|n
Tuesday|星期二|n
Wednesday|星期三|n
Thursday|星期四|n
Friday|星期五|n
Saturday|星期六|n
weekday|工作日|n
weekend|周末|n
February|二月|n
March|三月|n
April|四月|n
May|五月|n
June|六月|n
July|七月|n
August|八月|n
September|九月|n
October|十月|n
November|十一月|n
December|十二月|n
spring|春天|n
summer|夏天|n
autumn|秋天|n
fall|秋天|n
winter|冬天|n
season|季节|n
festival|节日|n
date|日期|n
calendar|日历|n
o'clock|点钟|adv
zero|零|num
=== colorshape ===
gray|灰色|adj
grey|灰色|adj
gold|金色|adj
silver|银色|adj
navy|海军蓝|adj
dark|深色的|adj
light|浅色的|adj
bright|明亮的|adj
pale|苍白的|adj
deep|深的|adj
line|线|n
dot|点|n
point|点|n
curve|曲线|n
angle|角|n
edge|边|n
corner|角落|n
side|边|n
surface|表面|n
wide|宽的|adj
narrow|窄的|adj
thick|厚的|adj
thin|薄的|adj
big|大的|adj
small|小的|adj
large|大的|adj
tiny|微小的|adj
huge|巨大的|adj
giant|巨大的|adj
tall|高的|adj
short|矮的|adj
long|长的|adj
deep|深的|adj
shallow|浅的|adj
round|圆的|adj
oval|椭圆的|adj
star|星形|n
heart|心形|n
cross|十字|n
sphere|球体|n
cube|立方体|n
cone|圆锥|n
cylinder|圆柱|n
pyramid|金字塔|n
ball|球|n
ring|环|n
ribbon|丝带|n
stripe|条纹|n
spot|斑点|n
mark|标记|n
sign|标志|n
symbol|符号|n
picture|图片|n
photo|照片|n
drawing|画|n
painting|绘画|n
image|图像|n
view|景色|n
scene|场景|n
frame|画框|n
mirror|镜子|n
glass|玻璃|n
plastic|塑料|n
wood|木头|n
metal|金属|n
cloth|布|n
fabric|织物|n
empty|空的|adj
full|满的|adj
heavy|重的|adj
hollow|空心的|adj
flat|平的|adj
sharp|锋利的|adj
=== action ===
walk|走|v
sit|坐|v
stand|站|v
lie|躺|v
sleep|睡|v
wake|醒来|v
dance|跳舞|v
play|玩|v
work|工作|v
rest|休息|v
exercise|锻炼|v
practice|练习|v
listen|听|v
look|看|v
watch|观看|v
see|看见|v
hear|听见|v
smell|闻|v
taste|品尝|v
feel|感觉|v
touch|触摸|v
hold|抓|v
carry|搬运|v
push|推|v
pull|拉|v
drop|掉|v
pick|挑|v
throw|扔|v
catch|接住|v
hit|打|v
kick|踢|v
hug|拥抱|v
kiss|亲吻|v
smile|微笑|v
laugh|笑|v
cry|哭|v
shout|喊|v
talk|谈话|v
speak|说|v
tell|告诉|v
ask|问|v
answer|回答|v
reply|回复|v
agree|同意|v
give|给|v
take|拿|v
send|送|v
receive|接收|v
buy|买|v
sell|卖|v
pay|支付|v
save|节省|v
spend|花费|v
find|找到|v
lose|丢失|v
search|搜索|v
win|赢|v
follow|跟随|v
lead|引导|v
chase|追逐|v
hide|隐藏|v
leave|离开|v
stay|停留|v
live|住|v
die|死|v
grow|生长|v
change|改变|v
become|成为|v
move|移动|v
like|喜欢|v
hate|讨厌|v
want|想要|v
need|需要|v
hope|希望|v
wish|希望|v
dream|梦想|v
think|想|v
know|知道|v
believe|相信|v
decide|决定|v
choose|选择|v
plan|计划|v
build|建造|v
make|制作|v
create|创造|v
fix|修理|v
break|打破|v
open|打开|v
close|关闭|v
scared|害怕的|adj
brave|勇敢的|adj
proud|骄傲的|adj
lonely|孤独的|adj
calm|平静的|adj
lazy|懒的|adj
healthy|健康的|adj
fast|快的|adj
lucky|幸运的|adj
"""

# ─────────────────────────  初中 1500+ 词  ─────────────────────────
MIDDLE = """\
=== basic ===
agree|同意|v
disagree|不同意|v
admit|承认|v
deny|否认|v
mention|提及|v
suggest|建议|v
advise|建议|v
explain|解释|v
imagine|想象|v
pretend|假装|v
forgive|原谅|v
apologize|道歉|v
appreciate|欣赏|v
reply|答复|v
respond|回应|v
discuss|讨论|v
debate|辩论|v
chat|聊天|v
greet|问候|v
nod|点头|v
wave|挥手|v
shrug|耸肩|v
positive|积极的|adj
negative|消极的|adj
patient|耐心的|adj
honest|诚实的|adj
fair|公平的|adj
wise|聪明的|adj
silly|傻的|adj
clever|聪明的|adj
serious|严肃的|adj
funny|有趣的|adj
boring|无聊的|adj
strange|奇怪的|adj
familiar|熟悉的|adj
common|常见的|adj
ordinary|普通的|adj
special|特别的|adj
particular|特别的|adj
necessary|必要的|adj
useful|有用的|adj
useless|无用的|adj
helpful|有帮助的|adj
typical|典型的|adj
similar|相似的|adj
different|不同的|adj
opposite|相反的|adj
exact|精确的|adj
proper|适当的|adj
suitable|合适的|adj
available|可用的|adj
possible|可能的|adj
impossible|不可能的|adj
likely|可能的|adj
unlikely|不可能的|adj
certain|确定的|adj
confident|自信的|adj
nervous|紧张的|adj
worried|担心的|adj
afraid|害怕的|adj
embarrassed|尴尬的|adj
ashamed|羞愧的|adj
guilty|内疚的|adj
satisfied|满意的|adj
pleased|高兴的|adj
delighted|愉快的|adj
amazed|惊奇的|adj
shocked|震惊的|adj
disappointed|失望的|adj
upset|烦恼的|adj
sensible|明智的|adj
mature|成熟的|adj
=== school ===
biology|生物|n
physics|物理|n
mathematics|数学|n
literature|文学|n
politics|政治|n
psychology|心理学|n
economics|经济学|n
philosophy|哲学|n
society|社会|n
culture|文化|n
education|教育|n
training|训练|n
research|研究|n
project|项目|n
experiment|实验|n
report|报告|n
essay|作文|n
thesis|论文|n
diploma|文凭|n
certificate|证书|n
syllabus|教学大纲|n
tuition|学费|n
graduate|毕业|v
admit|录取|v
enroll|注册|v
register|注册|v
attend|出席|v
participate|参加|v
discuss|讨论|v
analyze|分析|v
evaluate|评估|v
review|回顾|v
revise|修订|v
present|展示|v
publish|出版|v
quote|引用|v
debate|辩论|n
seminar|研讨会|n
lecture|讲座|n
workshop|工作坊|n
auditorium|礼堂|n
campus|校园|n
classroom|教室|n
laboratory|实验室|n
faculty|教职员|n
department|部门|n
chapter|章节|n
section|部分|n
paragraph|段落|n
introduction|引言|n
conclusion|结论|n
summary|总结|n
analysis|分析|n
solution|解决方案|n
formula|公式|n
calculation|计算|n
diagram|图表|n
graph|图表|n
chart|图|n
table|表格|n
illustration|插图|n
slide|幻灯片|n
presentation|演讲|n
speech|演讲|n
quiz|测验|n
midterm|期中考|n
final|期末考|n
result|结果|n
score|分数|n
performance|表现|n
behavior|行为|n
discipline|纪律|n
attendance|出勤|n
absence|缺席|n
deadline|截止日期|n
schedule|时间表|n
=== nature ===
animal|动物|n
plant|植物|n
species|物种|n
mammal|哺乳动物|n
reptile|爬行动物|n
amphibian|两栖动物|n
insect|昆虫|n
creature|生物|n
wildlife|野生动物|n
livestock|牲畜|n
herd|兽群|n
flock|鸟群|n
swarm|群|n
cattle|牛|n
poultry|家禽|n
cocoon|茧|n
nest|巢|n
shell|壳|n
fur|毛皮|n
feather|羽毛|n
fin|鳍|n
wing|翅膀|n
beak|喙|n
claw|爪|n
hoof|蹄|n
tail|尾巴|n
horn|角|n
trunk|象鼻|n
mane|鬃毛|n
scale|鳞|n
forest|森林|n
woodland|林地|n
prairie|大草原|n
plain|平原|n
canyon|峡谷|n
cliff|悬崖|n
peninsula|半岛|n
continent|大陆|n
glacier|冰川|n
volcano|火山|n
earthquake|地震|n
flood|洪水|n
drought|干旱|n
tornado|龙卷风|n
hurricane|飓风|n
typhoon|台风|n
breeze|微风|n
gust|阵风|n
storm|暴风雨|n
thunder|雷|n
lightning|闪电|n
hail|冰雹|n
mist|薄雾|n
frost|霜|n
dew|露|n
rainbow|彩虹|n
horizon|地平线|n
moonlight|月光|n
sunlight|阳光|n
shadow|影子|n
climate|气候|n
temperature|温度|n
humidity|湿度|n
weather|天气|n
season|季节|n
nature|自然|n
landscape|风景|n
scenery|风景|n
environment|环境|n
ecology|生态|n
ecosystem|生态系统|n
habitat|栖息地|n
resource|资源|n
mineral|矿物|n
crystal|水晶|n
rock|岩石|n
soil|土壤|n
clay|粘土|n
sand|沙子|n
mud|泥|n
dust|灰尘|n
=== food ===
diet|饮食|n
meal|餐|n
snack|零食|n
ingredient|原料|n
recipe|食谱|n
flavor|味道|n
spice|香料|n
herb|草药|n
seasoning|调味|n
nutrition|营养|n
vitamin|维生素|n
protein|蛋白质|n
calorie|卡路里|n
fiber|纤维|n
mineral|矿物质|n
allergy|过敏|n
diabetes|糖尿病|n
diet|节食|n
fast|斋戒|v
crave|渴望|v
chew|咀嚼|v
swallow|吞|v
sip|啜饮|v
gulp|大口喝|v
serve|上菜|v
order|点餐|v
deliver|送货|v
takeaway|外卖|n
delivery|外送|n
receipt|收据|n
tip|小费|n
menu|菜单|n
cuisine|菜肴|n
buffet|自助餐|n
cafeteria|食堂|n
canteen|餐厅|n
diner|餐馆|n
bistro|小酒馆|n
bakery|面包店|n
cafe|咖啡馆|n
deli|熟食店|n
grocery|杂货店|n
supermarket|超市|n
market|市场|n
spaghetti|意大利面|n
lasagna|千层面|n
sushi|寿司|n
sashimi|生鱼片|n
ramen|拉面|n
risotto|意式烩饭|n
omelette|蛋卷|n
pancake|薄煎饼|n
waffle|华夫饼|n
cereal|麦片|n
toast|吐司|n
bagel|百吉饼|n
muffin|松饼|n
brownie|布朗尼|n
truffle|松露|n
sausage|香肠|n
bacon|培根|n
ham|火腿|n
turkey|火鸡|n
duck|鸭|n
salmon|三文鱼|n
tuna|金枪鱼|n
oyster|牡蛎|n
lobster|龙虾|n
caviar|鱼子酱|n
syrup|糖浆|n
vinegar|醋|n
mayo|蛋黄酱|n
mustard|芥末|n
ketchup|番茄酱|n
soy|大豆|n
yogurt|酸奶|n
juice|果汁|n
soda|苏打水|n
=== family ===
relative|亲戚|n
ancestor|祖先|n
descendant|后代|n
spouse|配偶|n
fiance|未婚夫|n
fiancee|未婚妻|n
bride|新娘|n
groom|新郎|n
widow|寡妇|n
widower|鳏夫|n
orphan|孤儿|n
godfather|教父|n
godmother|教母|n
godchild|教子|n
stepfather|继父|n
stepmother|继母|n
stepsister|同父异母姐妹|n
stepbrother|同父异母兄弟|n
in-law|姻亲|n
generation|一代|n
household|家庭|n
youth|青年|n
adolescent|青少年|n
adult|成年人|n
elderly|老年人|n
senior|长者|n
junior|少年|n
infant|婴儿|n
toddler|学步孩童|n
teenager|青少年|n
teen|少年|n
peer|同辈|n
acquaintance|熟人|n
companion|伙伴|n
ally|盟友|n
rival|对手|n
enemy|敌人|n
opponent|对手|n
boyfriend|男朋友|n
girlfriend|女朋友|n
crush|暗恋|n
date|约会|n
relationship|关系|n
marriage|婚姻|n
divorce|离婚|n
wedding|婚礼|n
funeral|葬礼|n
ceremony|仪式|n
celebration|庆祝|n
gathering|聚会|n
reunion|团聚|n
neighborhood|社区|n
community|社区|n
society|社会|n
public|公众|n
crowd|人群|n
audience|观众|n
spectator|观众|n
participant|参与者|n
volunteer|志愿者|n
witness|目击者|n
victim|受害者|n
suspect|嫌疑人|n
criminal|罪犯|n
hero|英雄|n
heroine|女英雄|n
leader|领袖|n
follower|追随者|n
=== numtime ===
twentieth|第二十|num
hundredth|第一百|num
thousandth|第一千|num
once|一次|adv
twice|两次|adv
trice|三次|adv
double|双倍|adj
triple|三倍|adj
multiple|多个|adj
century|世纪|n
decade|十年|n
era|时代|n
millennium|千年|n
period|时期|n
duration|持续时间|n
moment|时刻|n
instant|瞬间|n
second|秒|n
millisecond|毫秒|n
nanosecond|纳秒|n
schedule|日程|n
agenda|议程|n
appointment|约定|n
deadline|截止日期|n
delay|延迟|n
postpone|推迟|v
reschedule|重新安排|v
expire|过期|v
overdue|逾期|adj
prompt|准时的|adj
punctual|准时的|adj
sequence|顺序|n
chronology|年代学|n
timeline|时间线|n
calendar|日历|n
festival|节日|n
ceremony|仪式|n
anniversary|周年|n
weekday|工作日|n
weekend|周末|n
fortnight|两周|n
quarter|季度|n
semester|学期|n
trimester|三个月|n
season|季节|n
springtime|春季|n
summertime|夏季|n
autumntime|秋季|n
wintertime|冬季|n
midnight|午夜|n
midday|正午|n
afternoon|下午|n
evening|傍晚|n
nightfall|黄昏|n
sunrise|日出|n
sunset|日落|n
twilight|薄暮|n
nightlife|夜生活|n
forever|永远|adv
constantly|不断地|adv
gradually|逐渐|adv
suddenly|突然|adv
immediately|立刻|adv
recently|最近|adv
currently|目前|adv
frequently|经常|adv
occasionally|偶尔|adv
regularly|定期|adv
=== colorshape ===
crimson|深红|adj
scarlet|猩红|adj
maroon|栗色|adj
turquoise|青绿色|adj
indigo|靛蓝|adj
violet|紫罗兰|adj
magenta|品红|adj
beige|米色|adj
ivory|象牙色|adj
khaki|卡其色|adj
cream|奶油色|adj
mint|薄荷绿|adj
charcoal|炭黑|adj
amber|琥珀色|adj
lavender|薰衣草色|adj
pastel|柔和色|adj
neon|霓虹色|adj
fluorescent|荧光的|adj
metallic|金属的|adj
matte|哑光的|adj
glossy|有光泽的|adj
shiny|闪亮的|adj
sparkling|闪闪发光的|adj
glittering|闪烁的|adj
glowing|发光的|adj
fade|褪色|v
shade|色调|n
hue|色彩|n
tint|淡色|n
tone|色调|n
shade|阴影|n
spectrum|光谱|n
palette|调色板|n
gradient|渐变|n
shape|形状|n
form|形式|n
figure|形|n
dimension|维度|n
proportion|比例|n
geometry|几何|n
geometric|几何的|adj
symmetric|对称的|adj
asymmetric|不对称的|adj
parallel|平行的|adj
perpendicular|垂直的|adj
diagonal|对角线|adj
horizontal|水平的|adj
vertical|垂直的|adj
curved|弯曲的|adj
straight|笔直的|adj
zigzag|之字形|adj
hexagon|六边形|n
octagon|八边形|n
pentagon|五角形|n
trapezoid|梯形|n
parallelogram|平行四边形|n
rhombus|菱形|n
quadrilateral|四边形|n
polygon|多边形|n
arc|弧|n
diameter|直径|n
radius|半径|n
circumference|周长|n
perimeter|周长|n
area|面积|n
volume|体积|n
height|高度|n
width|宽度|n
length|长度|n
depth|深度|n
=== action ===
achieve|达成|v
accomplish|完成|v
attempt|尝试|v
struggle|挣扎|v
overcome|克服|v
conquer|征服|v
defeat|击败|v
surrender|投降|v
escape|逃脱|v
rescue|营救|v
protect|保护|v
defend|防御|v
attack|攻击|v
threaten|威胁|v
warn|警告|v
encourage|鼓励|v
discourage|打消|v
motivate|激励|v
inspire|激发|v
influence|影响|v
persuade|说服|v
convince|说服|v
suggest|建议|v
recommend|推荐|v
require|要求|v
demand|要求|v
request|请求|v
beg|乞求|v
imagine|想象|v
pretend|假装|v
suppose|假设|v
consider|考虑|v
realize|意识|v
recognize|认出|v
discover|发现|v
explore|探索|v
investigate|调查|v
examine|检查|v
inspect|检查|v
observe|观察|v
witness|目击|v
notice|注意|v
ignore|忽视|v
neglect|忽视|v
focus|集中|v
concentrate|专注|v
distract|分心|v
remind|提醒|v
forget|忘记|v
recall|回忆|v
collect|收集|v
gather|聚集|v
organize|组织|v
arrange|安排|v
prepare|准备|v
finish|完成|v
complete|完成|v
fail|失败|v
succeed|成功|v
attempt|尝试|v
proceed|进行|v
continue|继续|v
pause|暂停|v
quit|退出|v
abandon|放弃|v
give-up|放弃|v
share|分享|v
divide|分|v
combine|组合|v
connect|连接|v
attach|附加|v
detach|分离|v
separate|分开|v
join|加入|v
unite|联合|v
split|分裂|v
mix|混合|v
blend|混合|v
match|搭配|v
compete|竞争|v
challenge|挑战|v
offer|提供|v
provide|提供|v
supply|供应|v
deliver|交付|v
exchange|交换|v
trade|交易|v
borrow|借|v
lend|借出|v
rent|租|v
hire|雇|v
employ|雇用|v
fire|解雇|v
quit|辞职|v
retire|退休|v
"""

# ─────────────────────────  高中 3000+ 词  ─────────────────────────
HIGH = """\
=== basic ===
acknowledge|承认|v
gratitude|感激|n
etiquette|礼节|n
hospitality|款待|n
sincere|真诚的|adj
courteous|有礼貌的|adj
considerate|体贴的|adj
diplomatic|圆滑的|adj
tactful|圆滑的|adj
reasonable|合理的|adj
rational|理性的|adj
logical|逻辑的|adj
philosophical|哲学的|adj
profound|深刻的|adj
superficial|肤浅的|adj
trivial|琐碎的|adj
significant|重要的|adj
substantial|实质的|adj
crucial|关键的|adj
essential|必要的|adj
fundamental|基本的|adj
vital|至关重要的|adj
critical|关键的|adj
indispensable|不可或缺的|adj
optional|可选的|adj
mandatory|强制的|adj
compulsory|强制的|adj
voluntary|自愿的|adj
spontaneous|自发的|adj
deliberate|故意的|adj
intentional|有意的|adj
arbitrary|任意的|adj
ambiguous|模糊的|adj
vague|含糊的|adj
explicit|明确的|adj
implicit|隐含的|adj
obvious|明显的|adj
apparent|明显的|adj
evident|明显的|adj
peculiar|奇特的|adj
eccentric|古怪的|adj
sophisticated|复杂的|adj
elegant|优雅的|adj
graceful|优雅的|adj
exquisite|精美的|adj
splendid|辉煌的|adj
magnificent|壮丽的|adj
stunning|令人惊叹的|adj
extraordinary|非凡的|adj
remarkable|非凡的|adj
exceptional|杰出的|adj
genuine|真正的|adj
authentic|真实的|adj
artificial|人造的|adj
synthetic|合成的|adj
fictitious|虚构的|adj
hypothetical|假设的|adj
theoretical|理论的|adj
empirical|经验的|adj
abstract|抽象的|adj
concrete|具体的|adj
=== school ===
academia|学术界|n
scholar|学者|n
academic|学者|n
intellectual|知识分子|n
discipline|学科|n
methodology|方法论|n
hypothesis|假设|n
theory|理论|n
principle|原则|n
doctrine|学说|n
paradigm|范式|n
framework|框架|n
analysis|分析|n
synthesis|综合|n
critique|批评|n
peer-review|同行评审|n
plagiarism|剽窃|n
citation|引用|n
bibliography|参考文献|n
dissertation|论文|n
thesis|论文|n
manuscript|手稿|n
abstract|摘要|n
journal|期刊|n
publication|出版物|n
treatise|论著|n
monograph|专著|n
anthology|文集|n
encyclopedia|百科全书|n
linguistics|语言学|n
phonetics|语音学|n
syntax|句法|n
grammar|语法|n
semantics|语义学|n
rhetoric|修辞学|n
literature|文学|n
prose|散文|n
verse|韵文|n
poetry|诗歌|n
drama|戏剧|n
sonnet|十四行诗|n
metaphor|隐喻|n
simile|明喻|n
allegory|寓言|n
satire|讽刺|n
irony|反讽|n
narrative|叙述|n
plot|情节|n
protagonist|主角|n
antagonist|反派|n
psychology|心理学|n
sociology|社会学|n
anthropology|人类学|n
archaeology|考古学|n
philosophy|哲学|n
ethics|伦理学|n
metaphysics|形而上学|n
epistemology|认识论|n
ideology|意识形态|n
phenomenon|现象|n
calculus|微积分|n
algebra|代数|n
geometry|几何|n
trigonometry|三角学|n
statistics|统计学|n
probability|概率|n
quantum|量子|n
relativity|相对论|n
thermodynamics|热力学|n
electromagnetism|电磁学|n
genetics|遗传学|n
biochemistry|生物化学|n
microbiology|微生物学|n
botany|植物学|n
zoology|动物学|n
astronomy|天文学|n
geology|地质学|n
oceanography|海洋学|n
meteorology|气象学|n
=== nature ===
biodiversity|生物多样性|n
ecosystem|生态系统|n
habitat|栖息地|n
biosphere|生物圈|n
biome|生物群落|n
flora|植物群|n
fauna|动物群|n
wildlife|野生动植物|n
endangered|濒危的|adj
extinct|灭绝的|adj
species|物种|n
genus|属|n
phylum|门|n
photosynthesis|光合作用|n
respiration|呼吸|n
metabolism|新陈代谢|n
evolution|进化|n
adaptation|适应|n
mutation|突变|n
hybrid|杂交|n
predator|捕食者|n
prey|猎物|n
parasite|寄生虫|n
symbiosis|共生|n
chlorophyll|叶绿素|n
pollen|花粉|n
spore|孢子|n
larva|幼虫|n
pupa|蛹|n
metamorphosis|变态|n
migration|迁徙|n
hibernation|冬眠|n
camouflage|伪装|n
mimicry|拟态|n
geography|地理|n
geology|地质学|n
topography|地形|n
terrain|地形|n
elevation|海拔|n
altitude|高度|n
latitude|纬度|n
longitude|经度|n
equator|赤道|n
hemisphere|半球|n
tropic|回归线|n
polar|极地的|adj
arctic|北极的|adj
antarctic|南极的|adj
tundra|苔原|n
savanna|稀树草原|n
rainforest|雨林|n
plateau|高原|n
peninsula|半岛|n
archipelago|群岛|n
strait|海峡|n
canal|运河|n
estuary|河口|n
delta|三角洲|n
basin|盆地|n
crater|火山口|n
geyser|间歇泉|n
glacier|冰川|n
iceberg|冰山|n
avalanche|雪崩|n
landslide|滑坡|n
tsunami|海啸|n
typhoon|台风|n
monsoon|季风|n
drought|干旱|n
famine|饥荒|n
deforestation|森林砍伐|n
desertification|沙漠化|n
pollution|污染|n
contamination|污染|n
emission|排放|n
greenhouse|温室|n
ozone|臭氧|n
sustainability|可持续性|n
conservation|保护|n
preservation|保存|n
restoration|恢复|n
=== food ===
cuisine|菜肴|n
gastronomy|美食学|n
culinary|烹饪的|adj
gourmet|美食家|n
delicacy|佳肴|n
appetizer|开胃菜|n
entree|主菜|n
dessert|甜点|n
beverage|饮料|n
condiment|调味品|n
seasoning|调味|n
marinade|腌料|n
garnish|装饰|n
dressing|调料|n
pastry|糕点|n
confectionery|糖果|n
truffle|松露|n
caviar|鱼子酱|n
foie-gras|鹅肝|n
prosciutto|火腿|n
salami|萨拉米|n
gourmet|美食家|n
sommelier|侍酒师|n
chef|厨师|n
waiter|服务员|n
maitre|领班|n
banquet|宴会|n
buffet|自助餐|n
catering|餐饮服务|n
takeout|外卖|n
brunch|早午餐|n
banquet|宴会|n
brewery|啤酒厂|n
distillery|酒厂|n
vineyard|葡萄园|n
orchard|果园|n
plantation|种植园|n
farmstead|农庄|n
ranch|牧场|n
greenhouse|温室|n
hydroponics|水培|n
organic|有机的|adj
vegan|严格素食|adj
vegetarian|素食|adj
gluten|麸质|n
lactose|乳糖|n
cholesterol|胆固醇|n
saturated|饱和的|adj
unsaturated|不饱和的|adj
preservative|防腐剂|n
additive|添加剂|n
flavoring|调味|n
aroma|香气|n
fragrance|香味|n
texture|质地|n
consistency|一致性|n
crunchy|脆的|adj
crispy|酥脆的|adj
chewy|耐嚼的|adj
juicy|多汁的|adj
tender|嫩的|adj
mellow|圆润的|adj
savory|可口的|adj
zesty|有趣味的|adj
hearty|丰盛的|adj
bland|平淡的|adj
exotic|异国的|adj
ethnic|民族的|adj
fusion|融合|n
seasonal|季节的|adj
homemade|自制的|adj
gourmet|美食的|adj
=== family ===
genealogy|家谱|n
lineage|血统|n
ancestry|祖籍|n
heritage|遗产|n
legacy|遗产|n
patriarch|族长|n
matriarch|女族长|n
dynasty|王朝|n
clan|宗族|n
tribe|部落|n
kinship|亲属关系|n
forefather|祖先|n
descendant|后裔|n
heir|继承人|n
heiress|女继承人|n
guardian|监护人|n
custodian|监护人|n
mentor|导师|n
protege|被保护人|n
godparent|教父母|n
marriage|婚姻|n
matrimony|婚姻|n
matrimonial|婚姻的|adj
nuptials|婚礼|n
honeymoon|蜜月|n
dowry|嫁妆|n
proposal|求婚|n
engagement|订婚|n
betrothal|订婚|n
fiancee|未婚妻|n
fiance|未婚夫|n
wedlock|婚姻|n
matrimonial|婚姻的|adj
divorce|离婚|n
separation|分居|n
estrangement|疏远|n
custody|监护权|n
alimony|赡养费|n
inheritance|继承|n
bequest|遗赠|n
testament|遗嘱|n
heritage|遗产|n
patrilineal|父系的|adj
matrilineal|母系的|adj
extended|大家庭|adj
nuclear|核心家庭|adj
blended|混合家庭|adj
adopted|收养的|adj
biological|生物的|adj
maternal|母方的|adj
paternal|父方的|adj
sibling|同胞|n
twin|双胞胎|n
triplet|三胞胎|n
quadruplet|四胞胎|n
intimate|亲密的|adj
companion|同伴|n
confidant|知己|n
soulmate|灵魂伴侣|n
acquaintance|相识|n
camaraderie|友情|n
fellowship|同志情谊|n
solidarity|团结|n
loyalty|忠诚|n
betrayal|背叛|n
=== numtime ===
chronology|年代学|n
chronicle|编年史|n
epoch|纪元|n
era|时代|n
millennium|千年|n
century|世纪|n
decade|十年|n
generation|一代|n
contemporary|当代的|adj
modern|现代的|adj
ancient|古代的|adj
prehistoric|史前的|adj
medieval|中世纪的|adj
renaissance|文艺复兴|n
victorian|维多利亚时代|adj
historical|历史的|adj
historic|历史性的|adj
chronological|按时间顺序|adj
sequential|连续的|adj
simultaneous|同时的|adj
concurrent|同时发生的|adj
synchronize|同步|v
asynchronous|异步的|adj
periodic|周期的|adj
intermittent|间歇的|adj
sporadic|偶发的|adj
perpetual|永久的|adj
eternal|永恒的|adj
infinite|无限的|adj
finite|有限的|adj
temporary|临时的|adj
permanent|永久的|adj
transient|短暂的|adj
fleeting|稍纵即逝的|adj
ephemeral|短暂的|adj
prolonged|长期的|adj
extended|延长的|adj
duration|持续时间|n
interval|间隔|n
hiatus|间断|n
respite|喘息|n
pause|暂停|n
delay|延迟|n
postponement|推迟|n
adjournment|休会|n
suspension|暂停|n
extension|延长|n
prolongation|延长|n
acceleration|加速|n
deceleration|减速|n
expedite|加快|v
hasten|赶快|v
linger|徘徊|v
procrastinate|拖延|v
anticipate|预期|v
expedient|权宜的|adj
imminent|即将的|adj
forthcoming|即将到来|adj
upcoming|即将到来|adj
prevailing|流行的|adj
emerging|新兴的|adj
obsolete|过时的|adj
outdated|过时的|adj
antiquated|陈旧的|adj
=== colorshape ===
chromatic|色彩的|adj
monochromatic|单色的|adj
polychromatic|多色的|adj
opaque|不透明的|adj
translucent|半透明的|adj
transparent|透明的|adj
luminous|发光的|adj
incandescent|白炽的|adj
phosphorescent|磷光的|adj
iridescent|彩虹色的|adj
opalescent|乳白色的|adj
pearlescent|珍珠般的|adj
prismatic|棱柱形的|adj
kaleidoscopic|万花筒般的|adj
psychedelic|迷幻的|adj
silhouette|剪影|n
outline|轮廓|n
contour|轮廓|n
profile|侧影|n
form|形式|n
configuration|配置|n
formation|形成|n
arrangement|布置|n
composition|构图|n
symmetry|对称|n
asymmetry|不对称|n
proportion|比例|n
ratio|比率|n
scale|比例|n
magnitude|量级|n
dimension|尺寸|n
geometry|几何|n
topology|拓扑|n
cylinder|圆柱|n
cone|圆锥|n
prism|棱柱|n
pyramid|金字塔|n
tetrahedron|四面体|n
octahedron|八面体|n
dodecahedron|十二面体|n
icosahedron|二十面体|n
sphere|球体|n
hemisphere|半球|n
ellipse|椭圆|n
ellipsoid|椭球体|n
parabola|抛物线|n
hyperbola|双曲线|n
asymptote|渐近线|n
tangent|切线|n
chord|弦|n
arc|弧|n
sector|扇形|n
segment|段|n
vertex|顶点|n
apex|顶点|n
fulcrum|支点|n
axis|轴|n
diameter|直径|n
radius|半径|n
circumference|圆周|n
volume|体积|n
density|密度|n
mass|质量|n
texture|质地|n
gradient|梯度|n
spectrum|光谱|n
hue|色调|n
saturation|饱和度|n
luminance|亮度|n
=== action ===
accomplish|完成|v
achieve|实现|v
attain|达到|v
endeavor|努力|v
strive|奋斗|v
persist|坚持|v
persevere|坚忍|v
yield|屈服|v
submit|屈服|v
surrender|投降|v
relinquish|放弃|v
abandon|放弃|v
forsake|抛弃|v
renounce|放弃|v
denounce|谴责|v
condemn|谴责|v
reproach|责备|v
rebuke|斥责|v
chastise|惩罚|v
admonish|训诫|v
counsel|劝告|v
advise|建议|v
deliberate|深思熟虑|v
contemplate|沉思|v
ponder|深思|v
meditate|冥想|v
ruminate|反思|v
speculate|推测|v
hypothesize|假设|v
postulate|假定|v
assume|假定|v
presume|推测|v
infer|推断|v
deduce|演绎|v
induce|归纳|v
extrapolate|推断|v
interpolate|插值|v
elaborate|详细说明|v
expound|阐释|v
expatiate|详谈|v
articulate|清晰表达|v
enunciate|发音|v
discourse|谈论|v
ascertain|确定|v
verify|核实|v
authenticate|认证|v
substantiate|证实|v
corroborate|证实|v
validate|证实|v
nullify|废除|v
annul|废除|v
revoke|撤销|v
rescind|废除|v
repeal|废除|v
abrogate|废除|v
mitigate|减轻|v
alleviate|减轻|v
ameliorate|改善|v
exacerbate|加剧|v
aggravate|加重|v
intensify|加强|v
reinforce|加强|v
augment|增加|v
amplify|放大|v
diminish|减少|v
dwindle|缩小|v
deteriorate|恶化|v
degenerate|衰退|v
regenerate|再生|v
rejuvenate|恢复活力|v
revitalize|振兴|v
restore|恢复|v
renovate|翻新|v
refurbish|翻新|v
renovate|更新|v
overhaul|彻底检查|v
inaugurate|就职|v
commence|开始|v
initiate|发起|v
embark|开始|v
undertake|承担|v
delegate|委派|v
relegate|降级|v
demote|降级|v
promote|晋升|v
advocate|倡导|v
champion|拥护|v
endorse|赞同|v
ratify|批准|v
sanction|批准|v
authorize|授权|v
empower|授权|v
"""


# ─────────────────────────  parser & merger  ─────────────────────────

def auto_example(word: str, meaning: str, pos: str):
    """根据词性生成短例句模板"""
    w = word.lower()
    if pos == "v":
        return f"I {w} every day.", f"我每天{meaning}。"
    if pos == "adj":
        return f"It is very {w}.", f"它非常{meaning}。"
    if pos == "adv":
        return f"He answered {w}.", f"他{meaning}地回答。"
    if pos == "int":
        return f"{word.capitalize()}!", f"{meaning}！"
    if pos == "num":
        return f"There are {w}.", f"有{meaning}。"
    if pos == "prep":
        return f"It is {w} the table.", f"它在桌子{meaning}。"
    if pos == "pron":
        return f"{word.capitalize()} is mine.", f"{meaning}是我的。"
    if pos == "conj":
        return f"A {w} B.", f"A {meaning} B。"
    # default n
    return f"This is a {w}.", f"这是一个{meaning}。"


def parse(text: str, level: str):
    out = []
    topic = None
    default_diff = {"primary": 1, "middle": 2, "high": 3}[level]
    for raw in text.split("\n"):
        line = raw.strip()
        if not line or line.startswith("//"):
            continue
        m = re.match(r"^=+\s*(\w+)\s*=+$", line)
        if m:
            topic = m.group(1)
            continue
        if topic is None:
            continue
        parts = [p.strip() for p in line.split("|")]
        if len(parts) < 2:
            continue
        word = parts[0]
        meaning = parts[1]
        pos = parts[2] if len(parts) > 2 and parts[2] else "n"
        diff = int(parts[3]) if len(parts) > 3 and parts[3] else default_diff
        ex_en, ex_zh = auto_example(word, meaning, pos)
        out.append({
            "word": word,
            "meaning": meaning,
            "pos": pos,
            "topic": topic,
            "difficulty": diff,
            "example": ex_en,
            "example_zh": ex_zh,
            "level": level,
        })
    return out


def merge_existing(new_list, level):
    """合并到已有 JSON：保留现有词条的高质量字段（音标/手写例句），追加新词。"""
    fp = OUT / f"{level}.json"
    if not fp.exists():
        return new_list
    try:
        existing = json.loads(fp.read_text(encoding="utf-8"))
    except Exception:
        return new_list

    by_word = {w["word"].lower(): w for w in existing}
    merged = []
    seen = set()
    for w in new_list:
        key = w["word"].lower()
        if key in seen:
            continue
        seen.add(key)
        if key in by_word:
            ex = dict(by_word[key])
            # 用新词条字段补全缺失（不覆盖已有的好字段）
            for k, v in w.items():
                ex.setdefault(k, v)
            merged.append(ex)
        else:
            merged.append(w)

    # 已有但本轮未涉及的词条原样保留
    for key, ex in by_word.items():
        if key not in seen:
            merged.append(ex)
    return merged


def write_json(items, fp: Path):
    fp.write_text(json.dumps(items, ensure_ascii=False, indent=1), encoding="utf-8")


def main():
    primary = merge_existing(parse(PRIMARY, "primary"), "primary")
    middle = merge_existing(parse(MIDDLE, "middle"), "middle")
    high = merge_existing(parse(HIGH, "high"), "high")

    write_json(primary, OUT / "primary.json")
    write_json(middle, OUT / "middle.json")
    write_json(high, OUT / "high.json")

    print(f"primary: {len(primary)} words")
    print(f"middle:  {len(middle)} words")
    print(f"high:    {len(high)} words")
    print(f"total:   {len(primary) + len(middle) + len(high)} words")


if __name__ == "__main__":
    main()
